Add snapshot function

diff --git a/luci-app-amlogic/root/usr/bin/openwrt-backup b/luci-app-amlogic/root/usr/bin/openwrt-backup
--- a/luci-app-amlogic/root/usr/bin/openwrt-backup
+++ b/luci-app-amlogic/root/usr/bin/openwrt-backup
@@ -7,6 +7,7 @@
 # Copyright (C) 2020 https://github.com/ophub/amlogic-s9xxx-openwrt
 #======================================================================
 
+SNAPSHOT_PRESTR=".snapshots/"
 BACKUP_DIR="/.reserved"
 BACKUP_NAME="openwrt_config.tar.gz"
 BACKUP_FILE="${BACKUP_DIR}/${BACKUP_NAME}"
@@ -177,11 +178,137 @@ print_list() {
     exit 0
 }
 
+list_snapshot() {
+    echo "----------------------------------------------------------------"
+    btrfs subvolume list -rt /
+    echo "----------------------------------------------------------------"
+    read -p "Press [ enter ] to return." q
+}
+
+create_snapshot() {
+    default_snap_name="etc-$(date +"%Y%m%d%H%M%S")"
+    echo "The default snapshot name is: ${default_snap_name}"
+    echo "If you want to modify the snapshot name, please enter it below. Cannot contain spaces."
+    echo "If you do not want to modify it, just press [ Enter ]. Or press the [ q ] key to go back directly."
+    while :;do
+        read -p "[${default_snap_name}] : " nname
+        if [ "${nname}" == "" ];then
+            snap_name="${default_snap_name}"
+            break
+        elif echo "${nname}" | grep -E "\s+" > /dev/null;then
+            echo "The name [${nname}] contains spaces, please re-enter!"
+            continue
+        elif [ "${nname}" == "q" ] || [ "${nname}" == "Q" ];then
+            return
+        else
+            if btrfs subvolume list -rt / | awk '{print $4}' | grep "^\\${SNAPSHOT_PRESTR}${nname}$" >/dev/null;then
+                echo "Name: [ ${nname} ] has been used, please re-enter!"
+                continue
+            else
+                snap_name="${nname}"
+                break
+            fi
+        fi
+    done
+
+    (  cd /
+    chattr -ia etc/config/fstab
+    btrfs subvolume snapshot -r /etc "${SNAPSHOT_PRESTR}${snap_name}"
+    if [ $? -eq 0 ];then
+        echo "The snapshot is created successfully: ${snap_name}"
+    else
+        echo "Snapshot creation failed!"
+    fi
+    )
+    read -p "Press [ enter ] to return." q
+}
+
+restore_snapshot() {
+    echo "Below are the existing etc snapshots, please enter the name of one of them."
+    echo "Tip: [ etc-000 ] This is the factory initial configuration."
+    echo "     [ etc-001 ] if it exists, it is the initial configuration after upgrading from the previous version."
+    echo "----------------------------------------------------------------"
+    btrfs subvolume list -rt /
+    echo "----------------------------------------------------------------"
+    read -p "Please enter the name of the snapshot to be restored (only the part after ${SNAPSHOT_PRESTR} needs to be entered): " snap_name
+    if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" > /dev/null;then
+        while :;do
+            echo "Once the snapshot is restored, the current [ /etc ] will be overwritten!"
+            read -p "Are you sure you want to restore the snapshot: [$snap_name]? y/n [n] " yn
+            case $yn in
+                y|Y)
+                    (
+                        cd /
+                        chattr -ia etc/config/fstab
+                        mv etc etc.backup
+                        btrfs subvolume snapshot "${SNAPSHOT_PRESTR}${snap_name}" etc
+                        if [ $? -eq 0 ];then
+                            btrfs subvolume delete -c etc.backup
+                            echo "The recovery is successful, please enter [ reboot ] to restart the system!"
+                        else
+                            rm -rf etc
+                            mv etc.backup etc
+                            echo "Recovery failed, [ etc ] has not changed!"
+                        fi
+                    )
+                    read -p "Press [ enter ] to return." q
+                    break
+                    ;;
+                *)  break
+                    ;;
+            esac
+        done
+    else
+        read -p "The snapshot name is incorrect, please run the program again! Press [ Enter ] to go back." q
+    fi
+}
+
+delete_snapshot() {
+    echo "Below are the existing [ etc ] snapshots, please enter the name of one of them."
+    echo "Tip: [ etc-000 ] This is the factory initial configuration (cannot be deleted)"
+    echo "     [ etc-001 ] if it exists, it is the initial configuration after upgrading from the previous version (cannot be deleted)"
+    echo "----------------------------------------------------------------"
+    btrfs subvolume list -rt /
+    echo "----------------------------------------------------------------"
+    read -p "Please enter the name of the snapshot to be deleted (only the part after ${SNAPSHOT_PRESTR} needs to be entered): " snap_name
+    if [ "${snap_name}" == "etc-000" ] || [ "${snap_name}" == "etc-001" ];then
+        read -p "The key snapshot cannot be deleted! Press [ enter ] to return." q
+    elif [ "${snap_name}" == "" ];then
+        read -p "Name is empty! Press [ enter ] to return." q
+    else
+        if btrfs subvolume list -rt / | grep "${SNAPSHOT_PRESTR}${snap_name}" > /dev/null;then
+            read -p "Are you sure you want to delete ${snap_name}? y/n [n] " yn
+            case $yn in
+                y|Y)
+                    (
+                        cd /
+                        btrfs subvolume delete -c "${SNAPSHOT_PRESTR}${snap_name}"
+                        if [ $? -eq 0 ];then
+                            echo "Snapshot [ ${snap_name} ] has been deleted."
+                        else
+                            echo "Snapshot [ ${snap_name} ] failed to delete!"
+                        fi
+                    )
+                    read -p "Press [ Enter ] to return." q
+                    ;;
+                *)  break
+                    ;;
+            esac
+        else
+            read -p "The name of the snapshot is incorrect, press [ Enter ] to return." q
+        fi
+    fi
+}
+
 print_help() {
     echo "Usage: $0  -b    [ backup ]"
     echo "       $0  -r    [ restore ]"
-    echo "       $0  -p    [ print backup list ]"
     echo "       $0  -g    [ generate fstab ]"
+    echo "       $0  -p    [ print backup list ]"
+    echo "       $0  -l    [ list snapshots ]"
+    echo "       $0  -c    [ create snapshot ]"
+    echo "       $0  -s    [ restore snapshot ]"
+    echo "       $0  -d    [ delete snapshot ]"
     echo "       $0  -h    [ help ]"
     echo "       $0  -q    [ quit ]"
     exit 0
@@ -192,44 +319,59 @@ menu() {
         clear
         cat <<EOF
 
-        ┌────────[ openwrt-backup ]────────┐
-        │                                  │
-        │        b. backup                 │
-        │        r. restore                │
-        │        p. print backup list      │
-        │        g. generate fstab         │
-        │                                  │
-        ╞══════════════════════════════════╡
-        │                                  │
-        │        h. help                   │
-        │        q. quit                   │
-        │                                  │
-        └──────────────────────────────────┘
+        ┌────────[ backup config ]────────┐
+        │                                 │
+        │       b. backup config          │
+        │       r. restore config         │
+        │       g. generate fstab         │
+        │       p. print backup list      │
+        │                                 │
+        ├─────[ Snapshot management ]─────┤
+        │                                 │
+        │       l. list snapshots         │
+        │       c. create snapshot        │
+        │       s. restore snapshot       │
+        │       d. delete snapshot        │
+        │                                 │
+        ╞═════════════════════════════════╡
+        │                                 │
+        │       h. help                   │
+        │       q. quit                   │
+        │                                 │
+        └─────────────────────────────────┘
 	
 EOF
         echo -ne "please select: [ ]\b\b"
         read select
-            case $select in
-            b | backup)      backup;;
-            r | restore)     restore
-                             gen_fstab;;
-            p | print_list)  print_list;;
-            g | gen_fstab)   gen_fstab;;
-            h | help)        print_help;;
-            q | quit)        exit 0;;
-            esac
+        case $select in
+            b | backup)            backup;;
+            r | restore)           restore
+                                   gen_fstab;;
+            g | gen_fstab)         gen_fstab;;
+            p | print_list)        print_list;;
+            l | list_snapshot)     list_snapshot;;
+            c | create_snapshot)   create_snapshot;;
+            s | restore_snapshot)  restore_snapshot;;
+            d | delete_snapshot)   delete_snapshot;;
+            h | help)              print_help;;
+            q | quit)              exit 0;;
+        esac
     done
 }
 
-getopts 'brpghq' opts
+getopts 'brgplcsdhq' opts
 case $opts in 
-    b | backup)      backup;;
-    r | restore)     restore
-                     gen_fstab;;
-    p | print_list)  print_list;;
-    g | gen_fstab)   gen_fstab;;
-    h | help)        print_help;;
-    q | quit)        exit 0;;
-    *)               menu;;
+    b | backup)            backup;;
+    r | restore)           restore
+                           gen_fstab;;
+    g | gen_fstab)         gen_fstab;;
+    p | print_list)        print_list;;
+    l | list_snapshot)     list_snapshot;;
+    c | create_snapshot)   create_snapshot;;
+    s | restore_snapshot)  restore_snapshot;;
+    d | delete_snapshot)   delete_snapshot;;
+    h | help)              print_help;;
+    q | quit)              exit 0;;
+    *)                     menu;;
 esac
 
